/* valaccodecontrolflowmodule.c generated by valac, the Vala compiler
 * generated from valaccodecontrolflowmodule.vala, do not modify */

/* valaccodecontrolflowmodule.vala
 *
 * Copyright (C) 2006-2011  Jürg Billeter
 * Copyright (C) 2006-2008  Raffaele Sandrini
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */

#include "valacodegen.h"
#include <vala.h>
#include <glib.h>
#include <valaccode.h>
#include <valagee.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_target_value_unref0(var) ((var == NULL) ? NULL : (var = (vala_target_value_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))

static gpointer vala_ccode_control_flow_module_parent_class = NULL;

static void vala_ccode_control_flow_module_real_visit_if_statement (ValaCodeVisitor* base,
                                                             ValaIfStatement* stmt);
static void vala_ccode_control_flow_module_visit_string_switch_statement (ValaCCodeControlFlowModule* self,
                                                                   ValaSwitchStatement* stmt);
static void vala_ccode_control_flow_module_real_visit_switch_statement (ValaCodeVisitor* base,
                                                                 ValaSwitchStatement* stmt);
static void vala_ccode_control_flow_module_real_visit_switch_label (ValaCodeVisitor* base,
                                                             ValaSwitchLabel* label);
static void vala_ccode_control_flow_module_real_visit_loop (ValaCodeVisitor* base,
                                                     ValaLoop* stmt);
static void vala_ccode_control_flow_module_real_visit_foreach_statement (ValaCodeVisitor* base,
                                                                  ValaForeachStatement* stmt);
static void vala_ccode_control_flow_module_real_visit_break_statement (ValaCodeVisitor* base,
                                                                ValaBreakStatement* stmt);
static void vala_ccode_control_flow_module_real_visit_continue_statement (ValaCodeVisitor* base,
                                                                   ValaContinueStatement* stmt);
static GType vala_ccode_control_flow_module_get_type_once (void);

static void
vala_ccode_control_flow_module_real_visit_if_statement (ValaCodeVisitor* base,
                                                        ValaIfStatement* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaCCodeFunction* _tmp0_;
	ValaCCodeFunction* _tmp1_;
	ValaExpression* _tmp2_;
	ValaExpression* _tmp3_;
	ValaCCodeExpression* _tmp4_;
	ValaBlock* _tmp5_;
	ValaBlock* _tmp6_;
	ValaBlock* _tmp7_;
	ValaBlock* _tmp8_;
	ValaCCodeFunction* _tmp13_;
	ValaCCodeFunction* _tmp14_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_if_statement_get_condition (stmt);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_get_cvalue (_tmp3_);
	vala_ccode_function_open_if (_tmp1_, _tmp4_);
	_tmp5_ = vala_if_statement_get_true_statement (stmt);
	_tmp6_ = _tmp5_;
	vala_code_node_emit ((ValaCodeNode*) _tmp6_, (ValaCodeGenerator*) self);
	_tmp7_ = vala_if_statement_get_false_statement (stmt);
	_tmp8_ = _tmp7_;
	if (_tmp8_ != NULL) {
		ValaCCodeFunction* _tmp9_;
		ValaCCodeFunction* _tmp10_;
		ValaBlock* _tmp11_;
		ValaBlock* _tmp12_;
		_tmp9_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp10_ = _tmp9_;
		vala_ccode_function_add_else (_tmp10_);
		_tmp11_ = vala_if_statement_get_false_statement (stmt);
		_tmp12_ = _tmp11_;
		vala_code_node_emit ((ValaCodeNode*) _tmp12_, (ValaCodeGenerator*) self);
	}
	_tmp13_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp14_ = _tmp13_;
	vala_ccode_function_close (_tmp14_);
}

static gpointer
_vala_ccode_node_ref0 (gpointer self)
{
	return self ? vala_ccode_node_ref (self) : NULL;
}

static gpointer
_vala_iterable_ref0 (gpointer self)
{
	return self ? vala_iterable_ref (self) : NULL;
}

static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static void
vala_ccode_control_flow_module_visit_string_switch_statement (ValaCCodeControlFlowModule* self,
                                                              ValaSwitchStatement* stmt)
{
	ValaTargetValue* temp_value = NULL;
	ValaExpression* _tmp0_;
	ValaExpression* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaTargetValue* _tmp4_;
	ValaCCodeExpression* ctemp = NULL;
	ValaTargetValue* _tmp5_;
	ValaCCodeExpression* _tmp6_;
	ValaCCodeExpression* _tmp7_;
	ValaCCodeAssignment* cinit = NULL;
	ValaCCodeExpression* _tmp8_;
	ValaExpression* _tmp9_;
	ValaExpression* _tmp10_;
	ValaCCodeExpression* _tmp11_;
	ValaCCodeAssignment* _tmp12_;
	ValaCCodeConstant* czero = NULL;
	ValaCCodeConstant* _tmp13_;
	ValaCCodeFunctionCall* free_call = NULL;
	ValaCCodeIdentifier* _tmp14_;
	ValaCCodeIdentifier* _tmp15_;
	ValaCCodeFunctionCall* _tmp16_;
	ValaCCodeFunctionCall* _tmp17_;
	ValaCCodeFunctionCall* _tmp18_;
	ValaCCodeExpression* _tmp19_;
	ValaCCodeBinaryExpression* cisnull = NULL;
	ValaCCodeConstant* _tmp20_;
	ValaCCodeConstant* _tmp21_;
	ValaCCodeExpression* _tmp22_;
	ValaCCodeBinaryExpression* _tmp23_;
	ValaCCodeBinaryExpression* _tmp24_;
	ValaCCodeFunctionCall* cquark = NULL;
	ValaCCodeIdentifier* _tmp25_;
	ValaCCodeIdentifier* _tmp26_;
	ValaCCodeFunctionCall* _tmp27_;
	ValaCCodeFunctionCall* _tmp28_;
	ValaCCodeFunctionCall* _tmp29_;
	ValaCCodeExpression* _tmp30_;
	ValaCCodeConditionalExpression* ccond = NULL;
	ValaCCodeBinaryExpression* _tmp31_;
	ValaCCodeConstant* _tmp32_;
	ValaCCodeConstant* _tmp33_;
	ValaCCodeFunctionCall* _tmp34_;
	ValaCCodeConditionalExpression* _tmp35_;
	ValaCCodeConditionalExpression* _tmp36_;
	gint label_temp_id = 0;
	gint _tmp37_;
	gint _tmp38_;
	ValaDataType* _tmp39_;
	ValaTargetValue* _tmp40_;
	gint label_count = 0;
	ValaCCodeFunction* _tmp82_;
	ValaCCodeFunction* _tmp83_;
	ValaCCodeAssignment* _tmp84_;
	ValaTargetValue* _tmp85_;
	ValaCCodeExpression* _tmp86_;
	ValaCCodeExpression* _tmp87_;
	ValaCCodeExpression* _tmp88_;
	ValaCCodeConditionalExpression* _tmp89_;
	ValaCCodeAssignment* _tmp90_;
	ValaCCodeFunction* _tmp91_;
	ValaCCodeFunction* _tmp92_;
	ValaCCodeAssignment* _tmp93_;
	ValaExpression* _tmp94_;
	ValaExpression* _tmp95_;
	ValaDataType* _tmp96_;
	ValaDataType* _tmp97_;
	gboolean _tmp98_;
	gboolean _tmp99_;
	ValaSwitchSection* default_section = NULL;
	gint n = 0;
	ValaSwitchSection* _tmp189_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_switch_statement_get_expression (stmt);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_expression_get_value_type (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_ccode_base_module_create_temp_value ((ValaCCodeBaseModule*) self, _tmp3_, FALSE, (ValaCodeNode*) stmt, NULL);
	temp_value = _tmp4_;
	_tmp5_ = temp_value;
	_tmp6_ = vala_get_cvalue_ (_tmp5_);
	_tmp7_ = _vala_ccode_node_ref0 (_tmp6_);
	ctemp = _tmp7_;
	_tmp8_ = ctemp;
	_tmp9_ = vala_switch_statement_get_expression (stmt);
	_tmp10_ = _tmp9_;
	_tmp11_ = vala_get_cvalue (_tmp10_);
	_tmp12_ = vala_ccode_assignment_new (_tmp8_, _tmp11_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
	cinit = _tmp12_;
	_tmp13_ = vala_ccode_constant_new ("0");
	czero = _tmp13_;
	_tmp14_ = vala_ccode_identifier_new ("g_free");
	_tmp15_ = _tmp14_;
	_tmp16_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp15_);
	_tmp17_ = _tmp16_;
	_vala_ccode_node_unref0 (_tmp15_);
	free_call = _tmp17_;
	_tmp18_ = free_call;
	_tmp19_ = ctemp;
	vala_ccode_function_call_add_argument (_tmp18_, _tmp19_);
	_tmp20_ = vala_ccode_constant_new ("NULL");
	_tmp21_ = _tmp20_;
	_tmp22_ = ctemp;
	_tmp23_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, (ValaCCodeExpression*) _tmp21_, _tmp22_);
	_tmp24_ = _tmp23_;
	_vala_ccode_node_unref0 (_tmp21_);
	cisnull = _tmp24_;
	_tmp25_ = vala_ccode_identifier_new ("g_quark_from_string");
	_tmp26_ = _tmp25_;
	_tmp27_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp26_);
	_tmp28_ = _tmp27_;
	_vala_ccode_node_unref0 (_tmp26_);
	cquark = _tmp28_;
	_tmp29_ = cquark;
	_tmp30_ = ctemp;
	vala_ccode_function_call_add_argument (_tmp29_, _tmp30_);
	_tmp31_ = cisnull;
	_tmp32_ = vala_ccode_constant_new ("0");
	_tmp33_ = _tmp32_;
	_tmp34_ = cquark;
	_tmp35_ = vala_ccode_conditional_expression_new ((ValaCCodeExpression*) _tmp31_, (ValaCCodeExpression*) _tmp33_, (ValaCCodeExpression*) _tmp34_);
	_tmp36_ = _tmp35_;
	_vala_ccode_node_unref0 (_tmp33_);
	ccond = _tmp36_;
	_tmp37_ = vala_ccode_base_module_get_next_temp_var_id ((ValaCCodeBaseModule*) self);
	_tmp38_ = _tmp37_;
	vala_ccode_base_module_set_next_temp_var_id ((ValaCCodeBaseModule*) self, _tmp38_ + 1);
	label_temp_id = _tmp38_;
	_tmp39_ = ((ValaCCodeBaseModule*) self)->gquark_type;
	_tmp40_ = vala_ccode_base_module_create_temp_value ((ValaCCodeBaseModule*) self, _tmp39_, TRUE, (ValaCodeNode*) stmt, NULL);
	_vala_target_value_unref0 (temp_value);
	temp_value = _tmp40_;
	label_count = 0;
	{
		ValaList* _section_list = NULL;
		ValaList* _tmp41_;
		ValaList* _tmp42_;
		gint _section_size = 0;
		ValaList* _tmp43_;
		gint _tmp44_;
		gint _tmp45_;
		gint _section_index = 0;
		_tmp41_ = vala_switch_statement_get_sections (stmt);
		_tmp42_ = _vala_iterable_ref0 (_tmp41_);
		_section_list = _tmp42_;
		_tmp43_ = _section_list;
		_tmp44_ = vala_collection_get_size ((ValaCollection*) _tmp43_);
		_tmp45_ = _tmp44_;
		_section_size = _tmp45_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp46_;
			gint _tmp47_;
			ValaSwitchSection* section = NULL;
			ValaList* _tmp48_;
			gpointer _tmp49_;
			ValaSwitchSection* _tmp50_;
			_section_index = _section_index + 1;
			_tmp46_ = _section_index;
			_tmp47_ = _section_size;
			if (!(_tmp46_ < _tmp47_)) {
				break;
			}
			_tmp48_ = _section_list;
			_tmp49_ = vala_list_get (_tmp48_, _section_index);
			section = (ValaSwitchSection*) _tmp49_;
			_tmp50_ = section;
			if (vala_switch_section_has_default_label (_tmp50_)) {
				_vala_code_node_unref0 (section);
				continue;
			}
			{
				ValaList* _label_list = NULL;
				ValaSwitchSection* _tmp51_;
				ValaList* _tmp52_;
				ValaList* _tmp53_;
				gint _label_size = 0;
				ValaList* _tmp54_;
				gint _tmp55_;
				gint _tmp56_;
				gint _label_index = 0;
				_tmp51_ = section;
				_tmp52_ = vala_switch_section_get_labels (_tmp51_);
				_tmp53_ = _vala_iterable_ref0 (_tmp52_);
				_label_list = _tmp53_;
				_tmp54_ = _label_list;
				_tmp55_ = vala_collection_get_size ((ValaCollection*) _tmp54_);
				_tmp56_ = _tmp55_;
				_label_size = _tmp56_;
				_label_index = -1;
				while (TRUE) {
					gint _tmp57_;
					gint _tmp58_;
					ValaSwitchLabel* label = NULL;
					ValaList* _tmp59_;
					gpointer _tmp60_;
					ValaSwitchLabel* _tmp61_;
					ValaExpression* _tmp62_;
					ValaExpression* _tmp63_;
					ValaCCodeExpression* cexpr = NULL;
					ValaSwitchLabel* _tmp64_;
					ValaExpression* _tmp65_;
					ValaExpression* _tmp66_;
					ValaCCodeExpression* _tmp67_;
					ValaCCodeExpression* _tmp68_;
					ValaCCodeExpression* _tmp69_;
					_label_index = _label_index + 1;
					_tmp57_ = _label_index;
					_tmp58_ = _label_size;
					if (!(_tmp57_ < _tmp58_)) {
						break;
					}
					_tmp59_ = _label_list;
					_tmp60_ = vala_list_get (_tmp59_, _label_index);
					label = (ValaSwitchLabel*) _tmp60_;
					_tmp61_ = label;
					_tmp62_ = vala_switch_label_get_expression (_tmp61_);
					_tmp63_ = _tmp62_;
					vala_code_node_emit ((ValaCodeNode*) _tmp63_, (ValaCodeGenerator*) self);
					_tmp64_ = label;
					_tmp65_ = vala_switch_label_get_expression (_tmp64_);
					_tmp66_ = _tmp65_;
					_tmp67_ = vala_get_cvalue (_tmp66_);
					_tmp68_ = _vala_ccode_node_ref0 (_tmp67_);
					cexpr = _tmp68_;
					_tmp69_ = cexpr;
					if (vala_ccode_base_module_is_constant_ccode_expression (_tmp69_)) {
						gchar* cname = NULL;
						gint _tmp70_;
						gint _tmp71_;
						gchar* _tmp72_;
						ValaCCodeFunction* _tmp73_;
						ValaCCodeFunction* _tmp74_;
						ValaDataType* _tmp75_;
						gchar* _tmp76_;
						gchar* _tmp77_;
						const gchar* _tmp78_;
						ValaCCodeConstant* _tmp79_;
						ValaCCodeVariableDeclarator* _tmp80_;
						ValaCCodeVariableDeclarator* _tmp81_;
						_tmp70_ = label_temp_id;
						_tmp71_ = label_count;
						label_count = _tmp71_ + 1;
						_tmp72_ = g_strdup_printf ("_tmp%d_label%d", _tmp70_, _tmp71_);
						cname = _tmp72_;
						_tmp73_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
						_tmp74_ = _tmp73_;
						_tmp75_ = ((ValaCCodeBaseModule*) self)->gquark_type;
						_tmp76_ = vala_get_ccode_name ((ValaCodeNode*) _tmp75_);
						_tmp77_ = _tmp76_;
						_tmp78_ = cname;
						_tmp79_ = czero;
						_tmp80_ = vala_ccode_variable_declarator_new (_tmp78_, (ValaCCodeExpression*) _tmp79_, NULL);
						_tmp81_ = _tmp80_;
						vala_ccode_function_add_declaration (_tmp74_, _tmp77_, (ValaCCodeDeclarator*) _tmp81_, VALA_CCODE_MODIFIERS_STATIC);
						_vala_ccode_node_unref0 (_tmp81_);
						_g_free0 (_tmp77_);
						_g_free0 (cname);
					}
					_vala_ccode_node_unref0 (cexpr);
					_vala_code_node_unref0 (label);
				}
				_vala_iterable_unref0 (_label_list);
			}
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	_tmp82_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp83_ = _tmp82_;
	_tmp84_ = cinit;
	vala_ccode_function_add_expression (_tmp83_, (ValaCCodeExpression*) _tmp84_);
	_tmp85_ = temp_value;
	_tmp86_ = vala_get_cvalue_ (_tmp85_);
	_tmp87_ = _vala_ccode_node_ref0 (_tmp86_);
	_vala_ccode_node_unref0 (ctemp);
	ctemp = _tmp87_;
	_tmp88_ = ctemp;
	_tmp89_ = ccond;
	_tmp90_ = vala_ccode_assignment_new (_tmp88_, (ValaCCodeExpression*) _tmp89_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
	_vala_ccode_node_unref0 (cinit);
	cinit = _tmp90_;
	_tmp91_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp92_ = _tmp91_;
	_tmp93_ = cinit;
	vala_ccode_function_add_expression (_tmp92_, (ValaCCodeExpression*) _tmp93_);
	_tmp94_ = vala_switch_statement_get_expression (stmt);
	_tmp95_ = _tmp94_;
	_tmp96_ = vala_expression_get_value_type (_tmp95_);
	_tmp97_ = _tmp96_;
	_tmp98_ = vala_data_type_get_value_owned (_tmp97_);
	_tmp99_ = _tmp98_;
	if (_tmp99_) {
		ValaCCodeFunction* _tmp100_;
		ValaCCodeFunction* _tmp101_;
		ValaCCodeFunctionCall* _tmp102_;
		_tmp100_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp101_ = _tmp100_;
		_tmp102_ = free_call;
		vala_ccode_function_add_expression (_tmp101_, (ValaCCodeExpression*) _tmp102_);
	}
	default_section = NULL;
	label_count = 0;
	n = 0;
	{
		ValaList* _section_list = NULL;
		ValaList* _tmp103_;
		ValaList* _tmp104_;
		gint _section_size = 0;
		ValaList* _tmp105_;
		gint _tmp106_;
		gint _tmp107_;
		gint _section_index = 0;
		_tmp103_ = vala_switch_statement_get_sections (stmt);
		_tmp104_ = _vala_iterable_ref0 (_tmp103_);
		_section_list = _tmp104_;
		_tmp105_ = _section_list;
		_tmp106_ = vala_collection_get_size ((ValaCollection*) _tmp105_);
		_tmp107_ = _tmp106_;
		_section_size = _tmp107_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp108_;
			gint _tmp109_;
			ValaSwitchSection* section = NULL;
			ValaList* _tmp110_;
			gpointer _tmp111_;
			ValaSwitchSection* _tmp112_;
			ValaCCodeBinaryExpression* cor = NULL;
			ValaCCodeFunction* _tmp179_;
			ValaCCodeFunction* _tmp180_;
			ValaCCodeConstant* _tmp181_;
			ValaCCodeConstant* _tmp182_;
			ValaCCodeFunction* _tmp183_;
			ValaCCodeFunction* _tmp184_;
			ValaSwitchSection* _tmp185_;
			ValaCCodeFunction* _tmp186_;
			ValaCCodeFunction* _tmp187_;
			gint _tmp188_;
			_section_index = _section_index + 1;
			_tmp108_ = _section_index;
			_tmp109_ = _section_size;
			if (!(_tmp108_ < _tmp109_)) {
				break;
			}
			_tmp110_ = _section_list;
			_tmp111_ = vala_list_get (_tmp110_, _section_index);
			section = (ValaSwitchSection*) _tmp111_;
			_tmp112_ = section;
			if (vala_switch_section_has_default_label (_tmp112_)) {
				ValaSwitchSection* _tmp113_;
				ValaSwitchSection* _tmp114_;
				_tmp113_ = section;
				_tmp114_ = _vala_code_node_ref0 (_tmp113_);
				_vala_code_node_unref0 (default_section);
				default_section = _tmp114_;
				_vala_code_node_unref0 (section);
				continue;
			}
			cor = NULL;
			{
				ValaList* _label_list = NULL;
				ValaSwitchSection* _tmp115_;
				ValaList* _tmp116_;
				ValaList* _tmp117_;
				gint _label_size = 0;
				ValaList* _tmp118_;
				gint _tmp119_;
				gint _tmp120_;
				gint _label_index = 0;
				_tmp115_ = section;
				_tmp116_ = vala_switch_section_get_labels (_tmp115_);
				_tmp117_ = _vala_iterable_ref0 (_tmp116_);
				_label_list = _tmp117_;
				_tmp118_ = _label_list;
				_tmp119_ = vala_collection_get_size ((ValaCollection*) _tmp118_);
				_tmp120_ = _tmp119_;
				_label_size = _tmp120_;
				_label_index = -1;
				while (TRUE) {
					gint _tmp121_;
					gint _tmp122_;
					ValaSwitchLabel* label = NULL;
					ValaList* _tmp123_;
					gpointer _tmp124_;
					ValaSwitchLabel* _tmp125_;
					ValaExpression* _tmp126_;
					ValaExpression* _tmp127_;
					ValaCCodeExpression* cexpr = NULL;
					ValaSwitchLabel* _tmp128_;
					ValaExpression* _tmp129_;
					ValaExpression* _tmp130_;
					ValaCCodeExpression* _tmp131_;
					ValaCCodeExpression* _tmp132_;
					ValaCCodeExpression* _tmp133_;
					ValaCCodeBinaryExpression* ccmp = NULL;
					ValaCCodeExpression* _tmp164_;
					ValaCCodeExpression* _tmp165_;
					ValaCCodeBinaryExpression* _tmp166_;
					ValaCCodeBinaryExpression* _tmp167_;
					_label_index = _label_index + 1;
					_tmp121_ = _label_index;
					_tmp122_ = _label_size;
					if (!(_tmp121_ < _tmp122_)) {
						break;
					}
					_tmp123_ = _label_list;
					_tmp124_ = vala_list_get (_tmp123_, _label_index);
					label = (ValaSwitchLabel*) _tmp124_;
					_tmp125_ = label;
					_tmp126_ = vala_switch_label_get_expression (_tmp125_);
					_tmp127_ = _tmp126_;
					vala_code_node_emit ((ValaCodeNode*) _tmp127_, (ValaCodeGenerator*) self);
					_tmp128_ = label;
					_tmp129_ = vala_switch_label_get_expression (_tmp128_);
					_tmp130_ = _tmp129_;
					_tmp131_ = vala_get_cvalue (_tmp130_);
					_tmp132_ = _vala_ccode_node_ref0 (_tmp131_);
					cexpr = _tmp132_;
					_tmp133_ = cexpr;
					if (vala_ccode_base_module_is_constant_ccode_expression (_tmp133_)) {
						ValaCCodeIdentifier* cname = NULL;
						gint _tmp134_;
						gint _tmp135_;
						gchar* _tmp136_;
						gchar* _tmp137_;
						ValaCCodeIdentifier* _tmp138_;
						ValaCCodeIdentifier* _tmp139_;
						ValaCCodeBinaryExpression* ccondition = NULL;
						ValaCCodeConstant* _tmp140_;
						ValaCCodeIdentifier* _tmp141_;
						ValaCCodeBinaryExpression* _tmp142_;
						ValaCCodeFunctionCall* ccall = NULL;
						ValaCCodeIdentifier* _tmp143_;
						ValaCCodeIdentifier* _tmp144_;
						ValaCCodeFunctionCall* _tmp145_;
						ValaCCodeFunctionCall* _tmp146_;
						ValaCCodeIdentifier* _tmp147_;
						ValaCCodeFunctionCall* _tmp148_;
						ValaCCodeAssignment* _tmp149_;
						ValaCCodeFunctionCall* _tmp150_;
						ValaCCodeExpression* _tmp151_;
						ValaCCodeBinaryExpression* _tmp152_;
						ValaCCodeIdentifier* _tmp153_;
						ValaCCodeAssignment* _tmp154_;
						ValaCCodeConditionalExpression* _tmp155_;
						_tmp134_ = label_temp_id;
						_tmp135_ = label_count;
						label_count = _tmp135_ + 1;
						_tmp136_ = g_strdup_printf ("_tmp%d_label%d", _tmp134_, _tmp135_);
						_tmp137_ = _tmp136_;
						_tmp138_ = vala_ccode_identifier_new (_tmp137_);
						_tmp139_ = _tmp138_;
						_g_free0 (_tmp137_);
						cname = _tmp139_;
						_tmp140_ = czero;
						_tmp141_ = cname;
						_tmp142_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_INEQUALITY, (ValaCCodeExpression*) _tmp140_, (ValaCCodeExpression*) _tmp141_);
						ccondition = _tmp142_;
						_tmp143_ = vala_ccode_identifier_new ("g_quark_from_static_string");
						_tmp144_ = _tmp143_;
						_tmp145_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp144_);
						_tmp146_ = _tmp145_;
						_vala_ccode_node_unref0 (_tmp144_);
						ccall = _tmp146_;
						_tmp147_ = cname;
						_tmp148_ = ccall;
						_tmp149_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp147_, (ValaCCodeExpression*) _tmp148_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
						_vala_ccode_node_unref0 (cinit);
						cinit = _tmp149_;
						_tmp150_ = ccall;
						_tmp151_ = cexpr;
						vala_ccode_function_call_add_argument (_tmp150_, _tmp151_);
						_tmp152_ = ccondition;
						_tmp153_ = cname;
						_tmp154_ = cinit;
						_tmp155_ = vala_ccode_conditional_expression_new ((ValaCCodeExpression*) _tmp152_, (ValaCCodeExpression*) _tmp153_, (ValaCCodeExpression*) _tmp154_);
						_vala_ccode_node_unref0 (cexpr);
						cexpr = (ValaCCodeExpression*) _tmp155_;
						_vala_ccode_node_unref0 (ccall);
						_vala_ccode_node_unref0 (ccondition);
						_vala_ccode_node_unref0 (cname);
					} else {
						ValaCCodeFunctionCall* ccall = NULL;
						ValaCCodeIdentifier* _tmp156_;
						ValaCCodeIdentifier* _tmp157_;
						ValaCCodeFunctionCall* _tmp158_;
						ValaCCodeFunctionCall* _tmp159_;
						ValaCCodeFunctionCall* _tmp160_;
						ValaCCodeExpression* _tmp161_;
						ValaCCodeFunctionCall* _tmp162_;
						ValaCCodeExpression* _tmp163_;
						_tmp156_ = vala_ccode_identifier_new ("g_quark_from_string");
						_tmp157_ = _tmp156_;
						_tmp158_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp157_);
						_tmp159_ = _tmp158_;
						_vala_ccode_node_unref0 (_tmp157_);
						ccall = _tmp159_;
						_tmp160_ = ccall;
						_tmp161_ = cexpr;
						vala_ccode_function_call_add_argument (_tmp160_, _tmp161_);
						_tmp162_ = ccall;
						_tmp163_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp162_);
						_vala_ccode_node_unref0 (cexpr);
						cexpr = _tmp163_;
						_vala_ccode_node_unref0 (ccall);
					}
					_tmp164_ = ctemp;
					_tmp165_ = cexpr;
					_tmp166_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_EQUALITY, _tmp164_, _tmp165_);
					ccmp = _tmp166_;
					_tmp167_ = cor;
					if (_tmp167_ == NULL) {
						ValaCCodeBinaryExpression* _tmp168_;
						ValaCCodeBinaryExpression* _tmp169_;
						_tmp168_ = ccmp;
						_tmp169_ = _vala_ccode_node_ref0 (_tmp168_);
						_vala_ccode_node_unref0 (cor);
						cor = _tmp169_;
					} else {
						ValaCCodeBinaryExpression* _tmp170_;
						ValaCCodeBinaryExpression* _tmp171_;
						ValaCCodeBinaryExpression* _tmp172_;
						_tmp170_ = cor;
						_tmp171_ = ccmp;
						_tmp172_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_OR, (ValaCCodeExpression*) _tmp170_, (ValaCCodeExpression*) _tmp171_);
						_vala_ccode_node_unref0 (cor);
						cor = _tmp172_;
					}
					_vala_ccode_node_unref0 (ccmp);
					_vala_ccode_node_unref0 (cexpr);
					_vala_code_node_unref0 (label);
				}
				_vala_iterable_unref0 (_label_list);
			}
			if (n > 0) {
				ValaCCodeFunction* _tmp173_;
				ValaCCodeFunction* _tmp174_;
				ValaCCodeBinaryExpression* _tmp175_;
				_tmp173_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp174_ = _tmp173_;
				_tmp175_ = cor;
				vala_ccode_function_else_if (_tmp174_, (ValaCCodeExpression*) _tmp175_);
			} else {
				ValaCCodeFunction* _tmp176_;
				ValaCCodeFunction* _tmp177_;
				ValaCCodeBinaryExpression* _tmp178_;
				_tmp176_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp177_ = _tmp176_;
				_tmp178_ = cor;
				vala_ccode_function_open_if (_tmp177_, (ValaCCodeExpression*) _tmp178_);
			}
			_tmp179_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp180_ = _tmp179_;
			_tmp181_ = vala_ccode_constant_new ("0");
			_tmp182_ = _tmp181_;
			vala_ccode_function_open_switch (_tmp180_, (ValaCCodeExpression*) _tmp182_);
			_vala_ccode_node_unref0 (_tmp182_);
			_tmp183_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp184_ = _tmp183_;
			vala_ccode_function_add_default (_tmp184_);
			_tmp185_ = section;
			vala_code_node_emit ((ValaCodeNode*) _tmp185_, (ValaCodeGenerator*) self);
			_tmp186_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp187_ = _tmp186_;
			vala_ccode_function_close (_tmp187_);
			_tmp188_ = n;
			n = _tmp188_ + 1;
			_vala_ccode_node_unref0 (cor);
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	_tmp189_ = default_section;
	if (_tmp189_ != NULL) {
		ValaCCodeFunction* _tmp192_;
		ValaCCodeFunction* _tmp193_;
		ValaCCodeConstant* _tmp194_;
		ValaCCodeConstant* _tmp195_;
		ValaCCodeFunction* _tmp196_;
		ValaCCodeFunction* _tmp197_;
		ValaSwitchSection* _tmp198_;
		ValaCCodeFunction* _tmp199_;
		ValaCCodeFunction* _tmp200_;
		if (n > 0) {
			ValaCCodeFunction* _tmp190_;
			ValaCCodeFunction* _tmp191_;
			_tmp190_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp191_ = _tmp190_;
			vala_ccode_function_add_else (_tmp191_);
		}
		_tmp192_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp193_ = _tmp192_;
		_tmp194_ = vala_ccode_constant_new ("0");
		_tmp195_ = _tmp194_;
		vala_ccode_function_open_switch (_tmp193_, (ValaCCodeExpression*) _tmp195_);
		_vala_ccode_node_unref0 (_tmp195_);
		_tmp196_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp197_ = _tmp196_;
		vala_ccode_function_add_default (_tmp197_);
		_tmp198_ = default_section;
		vala_code_node_emit ((ValaCodeNode*) _tmp198_, (ValaCodeGenerator*) self);
		_tmp199_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp200_ = _tmp199_;
		vala_ccode_function_close (_tmp200_);
	}
	if (n > 0) {
		ValaCCodeFunction* _tmp201_;
		ValaCCodeFunction* _tmp202_;
		_tmp201_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp202_ = _tmp201_;
		vala_ccode_function_close (_tmp202_);
	}
	_vala_code_node_unref0 (default_section);
	_vala_ccode_node_unref0 (ccond);
	_vala_ccode_node_unref0 (cquark);
	_vala_ccode_node_unref0 (cisnull);
	_vala_ccode_node_unref0 (free_call);
	_vala_ccode_node_unref0 (czero);
	_vala_ccode_node_unref0 (cinit);
	_vala_ccode_node_unref0 (ctemp);
	_vala_target_value_unref0 (temp_value);
}

static void
vala_ccode_control_flow_module_real_visit_switch_statement (ValaCodeVisitor* base,
                                                            ValaSwitchStatement* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaExpression* _tmp0_;
	ValaExpression* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDataType* _tmp3_;
	ValaDataType* _tmp4_;
	ValaCCodeFunction* _tmp5_;
	ValaCCodeFunction* _tmp6_;
	ValaExpression* _tmp7_;
	ValaExpression* _tmp8_;
	ValaCCodeExpression* _tmp9_;
	gboolean has_default = FALSE;
	ValaCCodeFunction* _tmp27_;
	ValaCCodeFunction* _tmp28_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_switch_statement_get_expression (stmt);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_expression_get_value_type (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = ((ValaCCodeBaseModule*) self)->string_type;
	if (vala_data_type_compatible (_tmp3_, _tmp4_)) {
		vala_ccode_control_flow_module_visit_string_switch_statement (self, stmt);
		return;
	}
	_tmp5_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = vala_switch_statement_get_expression (stmt);
	_tmp8_ = _tmp7_;
	_tmp9_ = vala_get_cvalue (_tmp8_);
	vala_ccode_function_open_switch (_tmp6_, _tmp9_);
	has_default = FALSE;
	{
		ValaList* _section_list = NULL;
		ValaList* _tmp10_;
		ValaList* _tmp11_;
		gint _section_size = 0;
		ValaList* _tmp12_;
		gint _tmp13_;
		gint _tmp14_;
		gint _section_index = 0;
		_tmp10_ = vala_switch_statement_get_sections (stmt);
		_tmp11_ = _vala_iterable_ref0 (_tmp10_);
		_section_list = _tmp11_;
		_tmp12_ = _section_list;
		_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
		_tmp14_ = _tmp13_;
		_section_size = _tmp14_;
		_section_index = -1;
		while (TRUE) {
			gint _tmp15_;
			gint _tmp16_;
			ValaSwitchSection* section = NULL;
			ValaList* _tmp17_;
			gpointer _tmp18_;
			ValaSwitchSection* _tmp19_;
			ValaSwitchSection* _tmp22_;
			_section_index = _section_index + 1;
			_tmp15_ = _section_index;
			_tmp16_ = _section_size;
			if (!(_tmp15_ < _tmp16_)) {
				break;
			}
			_tmp17_ = _section_list;
			_tmp18_ = vala_list_get (_tmp17_, _section_index);
			section = (ValaSwitchSection*) _tmp18_;
			_tmp19_ = section;
			if (vala_switch_section_has_default_label (_tmp19_)) {
				ValaCCodeFunction* _tmp20_;
				ValaCCodeFunction* _tmp21_;
				_tmp20_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp21_ = _tmp20_;
				vala_ccode_function_add_default (_tmp21_);
				has_default = TRUE;
			}
			_tmp22_ = section;
			vala_code_node_emit ((ValaCodeNode*) _tmp22_, (ValaCodeGenerator*) self);
			_vala_code_node_unref0 (section);
		}
		_vala_iterable_unref0 (_section_list);
	}
	if (!has_default) {
		ValaCCodeFunction* _tmp23_;
		ValaCCodeFunction* _tmp24_;
		ValaCCodeFunction* _tmp25_;
		ValaCCodeFunction* _tmp26_;
		_tmp23_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp24_ = _tmp23_;
		vala_ccode_function_add_default (_tmp24_);
		_tmp25_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp26_ = _tmp25_;
		vala_ccode_function_add_break (_tmp26_);
	}
	_tmp27_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp28_ = _tmp27_;
	vala_ccode_function_close (_tmp28_);
}

static void
vala_ccode_control_flow_module_real_visit_switch_label (ValaCodeVisitor* base,
                                                        ValaSwitchLabel* label)
{
	ValaCCodeControlFlowModule * self;
	ValaSwitchSection* _tmp0_;
	ValaSwitchSection* _tmp1_;
	ValaCodeNode* _tmp2_;
	ValaCodeNode* _tmp3_;
	ValaExpression* _tmp4_;
	ValaExpression* _tmp5_;
	ValaDataType* _tmp6_;
	ValaDataType* _tmp7_;
	ValaDataType* _tmp8_;
	ValaExpression* _tmp9_;
	ValaExpression* _tmp10_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (label != NULL);
	_tmp0_ = vala_switch_label_get_section (label);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_code_node_get_parent_node ((ValaCodeNode*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_switch_statement_get_expression (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, VALA_TYPE_SWITCH_STATEMENT, ValaSwitchStatement));
	_tmp5_ = _tmp4_;
	_tmp6_ = vala_expression_get_value_type (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = ((ValaCCodeBaseModule*) self)->string_type;
	if (vala_data_type_compatible (_tmp7_, _tmp8_)) {
		return;
	}
	_tmp9_ = vala_switch_label_get_expression (label);
	_tmp10_ = _tmp9_;
	if (_tmp10_ != NULL) {
		ValaExpression* _tmp11_;
		ValaExpression* _tmp12_;
		ValaExpression* _tmp13_;
		ValaExpression* _tmp14_;
		ValaCCodeFunction* _tmp15_;
		ValaCCodeFunction* _tmp16_;
		ValaExpression* _tmp17_;
		ValaExpression* _tmp18_;
		ValaCCodeExpression* _tmp19_;
		_tmp11_ = vala_switch_label_get_expression (label);
		_tmp12_ = _tmp11_;
		vala_code_node_emit ((ValaCodeNode*) _tmp12_, (ValaCodeGenerator*) self);
		_tmp13_ = vala_switch_label_get_expression (label);
		_tmp14_ = _tmp13_;
		vala_code_visitor_visit_end_full_expression ((ValaCodeVisitor*) self, _tmp14_);
		_tmp15_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp16_ = _tmp15_;
		_tmp17_ = vala_switch_label_get_expression (label);
		_tmp18_ = _tmp17_;
		_tmp19_ = vala_get_cvalue (_tmp18_);
		vala_ccode_function_add_case (_tmp16_, _tmp19_);
	}
}

static void
vala_ccode_control_flow_module_real_visit_loop (ValaCodeVisitor* base,
                                                ValaLoop* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaCodeContext* _tmp0_;
	ValaCodeContext* _tmp1_;
	ValaProfile _tmp2_;
	ValaProfile _tmp3_;
	ValaBlock* _tmp13_;
	ValaBlock* _tmp14_;
	ValaCCodeFunction* _tmp15_;
	ValaCCodeFunction* _tmp16_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_context ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = vala_code_context_get_profile (_tmp1_);
	_tmp3_ = _tmp2_;
	if (_tmp3_ == VALA_PROFILE_GOBJECT) {
		ValaCCodeFunction* _tmp4_;
		ValaCCodeFunction* _tmp5_;
		ValaCCodeConstant* _tmp6_;
		ValaCCodeConstant* _tmp7_;
		_tmp4_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp5_ = _tmp4_;
		_tmp6_ = vala_ccode_constant_new ("TRUE");
		_tmp7_ = _tmp6_;
		vala_ccode_function_open_while (_tmp5_, (ValaCCodeExpression*) _tmp7_);
		_vala_ccode_node_unref0 (_tmp7_);
	} else {
		ValaCCodeFile* _tmp8_;
		ValaCCodeFunction* _tmp9_;
		ValaCCodeFunction* _tmp10_;
		ValaCCodeConstant* _tmp11_;
		ValaCCodeConstant* _tmp12_;
		_tmp8_ = ((ValaCCodeBaseModule*) self)->cfile;
		vala_ccode_file_add_include (_tmp8_, "stdbool.h", FALSE);
		_tmp9_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp10_ = _tmp9_;
		_tmp11_ = vala_ccode_constant_new ("true");
		_tmp12_ = _tmp11_;
		vala_ccode_function_open_while (_tmp10_, (ValaCCodeExpression*) _tmp12_);
		_vala_ccode_node_unref0 (_tmp12_);
	}
	_tmp13_ = vala_loop_get_body (stmt);
	_tmp14_ = _tmp13_;
	vala_code_node_emit ((ValaCodeNode*) _tmp14_, (ValaCodeGenerator*) self);
	_tmp15_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp16_ = _tmp15_;
	vala_ccode_function_close (_tmp16_);
}

static void
vala_ccode_control_flow_module_real_visit_foreach_statement (ValaCodeVisitor* base,
                                                             ValaForeachStatement* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaCCodeFunction* _tmp0_;
	ValaCCodeFunction* _tmp1_;
	ValaLocalVariable* collection_backup = NULL;
	ValaLocalVariable* _tmp2_;
	ValaLocalVariable* _tmp3_;
	ValaLocalVariable* _tmp4_;
	ValaDataType* collection_type = NULL;
	ValaLocalVariable* _tmp5_;
	ValaDataType* _tmp6_;
	ValaDataType* _tmp7_;
	ValaDataType* _tmp8_;
	ValaArrayType* array_type = NULL;
	ValaDataType* _tmp9_;
	ValaArrayType* _tmp10_;
	ValaArrayType* _tmp11_;
	ValaLocalVariable* _tmp14_;
	ValaCCodeFunction* _tmp15_;
	ValaCCodeFunction* _tmp16_;
	ValaLocalVariable* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	ValaCCodeExpression* _tmp20_;
	ValaCCodeExpression* _tmp21_;
	ValaExpression* _tmp22_;
	ValaExpression* _tmp23_;
	ValaCCodeExpression* _tmp24_;
	gboolean _tmp25_ = FALSE;
	gboolean _tmp26_;
	gboolean _tmp27_;
	ValaExpression* _tmp34_;
	ValaExpression* _tmp35_;
	ValaDataType* _tmp36_;
	ValaDataType* _tmp37_;
	ValaCCodeFunction* _tmp388_;
	ValaCCodeFunction* _tmp389_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_function_open_block (_tmp1_);
	_tmp2_ = vala_foreach_statement_get_collection_variable (stmt);
	_tmp3_ = _tmp2_;
	_tmp4_ = _vala_code_node_ref0 (_tmp3_);
	collection_backup = _tmp4_;
	_tmp5_ = collection_backup;
	_tmp6_ = vala_variable_get_variable_type ((ValaVariable*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = _vala_code_node_ref0 (_tmp7_);
	collection_type = _tmp8_;
	_tmp9_ = collection_type;
	_tmp10_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp9_, VALA_TYPE_ARRAY_TYPE) ? ((ValaArrayType*) _tmp9_) : NULL);
	array_type = _tmp10_;
	_tmp11_ = array_type;
	if (_tmp11_ != NULL) {
		ValaArrayType* _tmp12_;
		ValaArrayType* _tmp13_;
		_tmp12_ = array_type;
		vala_array_type_set_inline_allocated (_tmp12_, FALSE);
		_tmp13_ = array_type;
		vala_array_type_set_fixed_length (_tmp13_, FALSE);
	}
	_tmp14_ = collection_backup;
	vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp14_);
	_tmp15_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp16_ = _tmp15_;
	_tmp17_ = collection_backup;
	_tmp18_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = vala_foreach_statement_get_collection (stmt);
	_tmp23_ = _tmp22_;
	_tmp24_ = vala_get_cvalue (_tmp23_);
	vala_ccode_function_add_assignment (_tmp16_, _tmp21_, _tmp24_);
	_vala_ccode_node_unref0 (_tmp21_);
	_g_free0 (_tmp19_);
	_tmp26_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) stmt);
	_tmp27_ = _tmp26_;
	if (_tmp27_) {
		ValaExpression* _tmp28_;
		ValaExpression* _tmp29_;
		gboolean _tmp30_;
		gboolean _tmp31_;
		_tmp28_ = vala_foreach_statement_get_collection (stmt);
		_tmp29_ = _tmp28_;
		_tmp30_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) _tmp29_);
		_tmp31_ = _tmp30_;
		_tmp25_ = _tmp31_;
	} else {
		_tmp25_ = FALSE;
	}
	if (_tmp25_) {
		ValaExpression* _tmp32_;
		ValaExpression* _tmp33_;
		_tmp32_ = vala_foreach_statement_get_collection (stmt);
		_tmp33_ = _tmp32_;
		vala_ccode_base_module_add_simple_check ((ValaCCodeBaseModule*) self, (ValaCodeNode*) _tmp33_, FALSE);
	}
	_tmp34_ = vala_foreach_statement_get_collection (stmt);
	_tmp35_ = _tmp34_;
	_tmp36_ = vala_expression_get_value_type (_tmp35_);
	_tmp37_ = _tmp36_;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp37_, VALA_TYPE_ARRAY_TYPE)) {
		ValaExpression* _tmp38_;
		ValaExpression* _tmp39_;
		ValaDataType* _tmp40_;
		ValaDataType* _tmp41_;
		ValaArrayType* _tmp42_;
		ValaCCodeExpression* array_len = NULL;
		ValaLocalVariable* _tmp43_;
		gchar* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		gchar* _tmp47_;
		ValaCCodeExpression* _tmp48_;
		ValaCCodeExpression* _tmp49_;
		ValaCCodeFunction* _tmp50_;
		ValaCCodeFunction* _tmp51_;
		ValaCCodeExpression* _tmp52_;
		ValaExpression* _tmp53_;
		ValaExpression* _tmp54_;
		ValaCCodeExpression* _tmp55_;
		ValaCCodeExpression* _tmp56_;
		ValaLocalVariable* iterator_variable = NULL;
		ValaArrayType* _tmp57_;
		ValaDataType* _tmp58_;
		ValaDataType* _tmp59_;
		ValaDataType* _tmp60_;
		ValaDataType* _tmp61_;
		const gchar* _tmp62_;
		const gchar* _tmp63_;
		gchar* _tmp64_;
		gchar* _tmp65_;
		ValaLocalVariable* _tmp66_;
		ValaLocalVariable* _tmp67_;
		ValaLocalVariable* _tmp68_;
		gchar* it_name = NULL;
		ValaLocalVariable* _tmp69_;
		gchar* _tmp70_;
		ValaCCodeBinaryExpression* ccond = NULL;
		const gchar* _tmp71_;
		ValaCCodeExpression* _tmp72_;
		ValaCCodeExpression* _tmp73_;
		ValaCCodeExpression* _tmp74_;
		ValaCCodeBinaryExpression* _tmp75_;
		ValaCCodeBinaryExpression* _tmp76_;
		ValaCCodeFunction* _tmp77_;
		ValaCCodeFunction* _tmp78_;
		const gchar* _tmp79_;
		ValaCCodeExpression* _tmp80_;
		ValaCCodeExpression* _tmp81_;
		ValaCCodeConstant* _tmp82_;
		ValaCCodeConstant* _tmp83_;
		ValaCCodeAssignment* _tmp84_;
		ValaCCodeAssignment* _tmp85_;
		ValaCCodeBinaryExpression* _tmp86_;
		const gchar* _tmp87_;
		ValaCCodeExpression* _tmp88_;
		ValaCCodeExpression* _tmp89_;
		const gchar* _tmp90_;
		ValaCCodeExpression* _tmp91_;
		ValaCCodeExpression* _tmp92_;
		ValaCCodeConstant* _tmp93_;
		ValaCCodeConstant* _tmp94_;
		ValaCCodeBinaryExpression* _tmp95_;
		ValaCCodeBinaryExpression* _tmp96_;
		ValaCCodeAssignment* _tmp97_;
		ValaCCodeAssignment* _tmp98_;
		ValaCCodeExpression* element_expr = NULL;
		ValaLocalVariable* _tmp99_;
		gchar* _tmp100_;
		gchar* _tmp101_;
		ValaCCodeExpression* _tmp102_;
		ValaCCodeExpression* _tmp103_;
		const gchar* _tmp104_;
		ValaCCodeExpression* _tmp105_;
		ValaCCodeExpression* _tmp106_;
		ValaCCodeElementAccess* _tmp107_;
		ValaCCodeExpression* _tmp108_;
		ValaDataType* element_type = NULL;
		ValaArrayType* _tmp109_;
		ValaDataType* _tmp110_;
		ValaDataType* _tmp111_;
		ValaDataType* _tmp112_;
		ValaDataType* _tmp113_;
		ValaDataType* _tmp114_;
		ValaCCodeExpression* _tmp115_;
		ValaGLibValue* _tmp116_;
		ValaGLibValue* _tmp117_;
		ValaDataType* _tmp118_;
		ValaDataType* _tmp119_;
		ValaTargetValue* _tmp120_;
		ValaTargetValue* _tmp121_;
		ValaCCodeExpression* _tmp122_;
		ValaCCodeExpression* _tmp123_;
		ValaLocalVariable* _tmp124_;
		ValaLocalVariable* _tmp125_;
		ValaCCodeFunction* _tmp126_;
		ValaCCodeFunction* _tmp127_;
		ValaLocalVariable* _tmp128_;
		ValaLocalVariable* _tmp129_;
		gchar* _tmp130_;
		gchar* _tmp131_;
		ValaCCodeExpression* _tmp132_;
		ValaCCodeExpression* _tmp133_;
		ValaCCodeExpression* _tmp134_;
		ValaDataType* _tmp135_;
		ValaDataType* _tmp136_;
		ValaBlock* _tmp157_;
		ValaBlock* _tmp158_;
		ValaCCodeFunction* _tmp159_;
		ValaCCodeFunction* _tmp160_;
		_tmp38_ = vala_foreach_statement_get_collection (stmt);
		_tmp39_ = _tmp38_;
		_tmp40_ = vala_expression_get_value_type (_tmp39_);
		_tmp41_ = _tmp40_;
		_tmp42_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp41_, VALA_TYPE_ARRAY_TYPE, ValaArrayType));
		_vala_code_node_unref0 (array_type);
		array_type = _tmp42_;
		_tmp43_ = collection_backup;
		_tmp44_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp45_, 1);
		_tmp47_ = _tmp46_;
		_tmp48_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp47_);
		_tmp49_ = _tmp48_;
		_g_free0 (_tmp47_);
		_g_free0 (_tmp45_);
		array_len = _tmp49_;
		_tmp50_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp51_ = _tmp50_;
		_tmp52_ = array_len;
		_tmp53_ = vala_foreach_statement_get_collection (stmt);
		_tmp54_ = _tmp53_;
		_tmp55_ = vala_ccode_base_module_get_array_length_cexpression ((ValaCCodeBaseModule*) self, _tmp54_, -1);
		_tmp56_ = _tmp55_;
		vala_ccode_function_add_assignment (_tmp51_, _tmp52_, _tmp56_);
		_vala_ccode_node_unref0 (_tmp56_);
		_tmp57_ = array_type;
		_tmp58_ = vala_array_type_get_length_type (_tmp57_);
		_tmp59_ = _tmp58_;
		_tmp60_ = vala_data_type_copy (_tmp59_);
		_tmp61_ = _tmp60_;
		_tmp62_ = vala_foreach_statement_get_variable_name (stmt);
		_tmp63_ = _tmp62_;
		_tmp64_ = g_strconcat (_tmp63_, "_it", NULL);
		_tmp65_ = _tmp64_;
		_tmp66_ = vala_local_variable_new (_tmp61_, _tmp65_, NULL, NULL);
		_tmp67_ = _tmp66_;
		_g_free0 (_tmp65_);
		_vala_code_node_unref0 (_tmp61_);
		iterator_variable = _tmp67_;
		_tmp68_ = iterator_variable;
		vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp68_);
		_tmp69_ = iterator_variable;
		_tmp70_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp69_);
		it_name = _tmp70_;
		_tmp71_ = it_name;
		_tmp72_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp71_);
		_tmp73_ = _tmp72_;
		_tmp74_ = array_len;
		_tmp75_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_LESS_THAN, _tmp73_, _tmp74_);
		_tmp76_ = _tmp75_;
		_vala_ccode_node_unref0 (_tmp73_);
		ccond = _tmp76_;
		_tmp77_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp78_ = _tmp77_;
		_tmp79_ = it_name;
		_tmp80_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp79_);
		_tmp81_ = _tmp80_;
		_tmp82_ = vala_ccode_constant_new ("0");
		_tmp83_ = _tmp82_;
		_tmp84_ = vala_ccode_assignment_new (_tmp81_, (ValaCCodeExpression*) _tmp83_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp85_ = _tmp84_;
		_tmp86_ = ccond;
		_tmp87_ = it_name;
		_tmp88_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp87_);
		_tmp89_ = _tmp88_;
		_tmp90_ = it_name;
		_tmp91_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp90_);
		_tmp92_ = _tmp91_;
		_tmp93_ = vala_ccode_constant_new ("1");
		_tmp94_ = _tmp93_;
		_tmp95_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_PLUS, _tmp92_, (ValaCCodeExpression*) _tmp94_);
		_tmp96_ = _tmp95_;
		_tmp97_ = vala_ccode_assignment_new (_tmp89_, (ValaCCodeExpression*) _tmp96_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
		_tmp98_ = _tmp97_;
		vala_ccode_function_open_for (_tmp78_, (ValaCCodeExpression*) _tmp85_, (ValaCCodeExpression*) _tmp86_, (ValaCCodeExpression*) _tmp98_);
		_vala_ccode_node_unref0 (_tmp98_);
		_vala_ccode_node_unref0 (_tmp96_);
		_vala_ccode_node_unref0 (_tmp94_);
		_vala_ccode_node_unref0 (_tmp92_);
		_vala_ccode_node_unref0 (_tmp89_);
		_vala_ccode_node_unref0 (_tmp85_);
		_vala_ccode_node_unref0 (_tmp83_);
		_vala_ccode_node_unref0 (_tmp81_);
		_tmp99_ = collection_backup;
		_tmp100_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp99_);
		_tmp101_ = _tmp100_;
		_tmp102_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp101_);
		_tmp103_ = _tmp102_;
		_tmp104_ = it_name;
		_tmp105_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp104_);
		_tmp106_ = _tmp105_;
		_tmp107_ = vala_ccode_element_access_new (_tmp103_, _tmp106_);
		_tmp108_ = (ValaCCodeExpression*) _tmp107_;
		_vala_ccode_node_unref0 (_tmp106_);
		_vala_ccode_node_unref0 (_tmp103_);
		_g_free0 (_tmp101_);
		element_expr = _tmp108_;
		_tmp109_ = array_type;
		_tmp110_ = vala_array_type_get_element_type (_tmp109_);
		_tmp111_ = _tmp110_;
		_tmp112_ = vala_data_type_copy (_tmp111_);
		element_type = _tmp112_;
		_tmp113_ = element_type;
		vala_data_type_set_value_owned (_tmp113_, FALSE);
		_tmp114_ = element_type;
		_tmp115_ = element_expr;
		_tmp116_ = vala_glib_value_new (_tmp114_, _tmp115_, TRUE);
		_tmp117_ = _tmp116_;
		_tmp118_ = vala_foreach_statement_get_type_reference (stmt);
		_tmp119_ = _tmp118_;
		_tmp120_ = vala_ccode_base_module_transform_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp117_, _tmp119_, (ValaCodeNode*) stmt);
		_tmp121_ = _tmp120_;
		_tmp122_ = vala_get_cvalue_ (_tmp121_);
		_tmp123_ = _vala_ccode_node_ref0 (_tmp122_);
		_vala_ccode_node_unref0 (element_expr);
		element_expr = _tmp123_;
		_vala_target_value_unref0 (_tmp121_);
		_vala_target_value_unref0 (_tmp117_);
		_tmp124_ = vala_foreach_statement_get_element_variable (stmt);
		_tmp125_ = _tmp124_;
		vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp125_);
		_tmp126_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp127_ = _tmp126_;
		_tmp128_ = vala_foreach_statement_get_element_variable (stmt);
		_tmp129_ = _tmp128_;
		_tmp130_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp129_);
		_tmp131_ = _tmp130_;
		_tmp132_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp131_);
		_tmp133_ = _tmp132_;
		_tmp134_ = element_expr;
		vala_ccode_function_add_assignment (_tmp127_, _tmp133_, _tmp134_);
		_vala_ccode_node_unref0 (_tmp133_);
		_g_free0 (_tmp131_);
		_tmp135_ = vala_foreach_statement_get_type_reference (stmt);
		_tmp136_ = _tmp135_;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp136_, VALA_TYPE_ARRAY_TYPE)) {
			ValaArrayType* inner_array_type = NULL;
			ValaDataType* _tmp137_;
			ValaDataType* _tmp138_;
			ValaArrayType* _tmp139_;
			_tmp137_ = vala_foreach_statement_get_type_reference (stmt);
			_tmp138_ = _tmp137_;
			_tmp139_ = _vala_code_node_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp138_, VALA_TYPE_ARRAY_TYPE, ValaArrayType));
			inner_array_type = _tmp139_;
			{
				gint dim = 0;
				dim = 1;
				{
					gboolean _tmp140_ = FALSE;
					_tmp140_ = TRUE;
					while (TRUE) {
						ValaArrayType* _tmp142_;
						gint _tmp143_;
						gint _tmp144_;
						ValaCCodeFunction* _tmp145_;
						ValaCCodeFunction* _tmp146_;
						ValaLocalVariable* _tmp147_;
						ValaLocalVariable* _tmp148_;
						gchar* _tmp149_;
						gchar* _tmp150_;
						gchar* _tmp151_;
						gchar* _tmp152_;
						ValaCCodeExpression* _tmp153_;
						ValaCCodeExpression* _tmp154_;
						ValaCCodeConstant* _tmp155_;
						ValaCCodeConstant* _tmp156_;
						if (!_tmp140_) {
							gint _tmp141_;
							_tmp141_ = dim;
							dim = _tmp141_ + 1;
						}
						_tmp140_ = FALSE;
						_tmp142_ = inner_array_type;
						_tmp143_ = vala_array_type_get_rank (_tmp142_);
						_tmp144_ = _tmp143_;
						if (!(dim <= _tmp144_)) {
							break;
						}
						_tmp145_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
						_tmp146_ = _tmp145_;
						_tmp147_ = vala_foreach_statement_get_element_variable (stmt);
						_tmp148_ = _tmp147_;
						_tmp149_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp148_);
						_tmp150_ = _tmp149_;
						_tmp151_ = vala_ccode_base_module_get_array_length_cname ((ValaCCodeBaseModule*) self, _tmp150_, dim);
						_tmp152_ = _tmp151_;
						_tmp153_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp152_);
						_tmp154_ = _tmp153_;
						_tmp155_ = vala_ccode_constant_new ("-1");
						_tmp156_ = _tmp155_;
						vala_ccode_function_add_assignment (_tmp146_, _tmp154_, (ValaCCodeExpression*) _tmp156_);
						_vala_ccode_node_unref0 (_tmp156_);
						_vala_ccode_node_unref0 (_tmp154_);
						_g_free0 (_tmp152_);
						_g_free0 (_tmp150_);
					}
				}
			}
			_vala_code_node_unref0 (inner_array_type);
		}
		_tmp157_ = vala_foreach_statement_get_body (stmt);
		_tmp158_ = _tmp157_;
		vala_code_node_emit ((ValaCodeNode*) _tmp158_, (ValaCodeGenerator*) self);
		_tmp159_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
		_tmp160_ = _tmp159_;
		vala_ccode_function_close (_tmp160_);
		_vala_code_node_unref0 (element_type);
		_vala_ccode_node_unref0 (element_expr);
		_vala_ccode_node_unref0 (ccond);
		_g_free0 (it_name);
		_vala_code_node_unref0 (iterator_variable);
		_vala_ccode_node_unref0 (array_len);
	} else {
		gboolean _tmp161_ = FALSE;
		ValaExpression* _tmp162_;
		ValaExpression* _tmp163_;
		ValaDataType* _tmp164_;
		ValaDataType* _tmp165_;
		ValaClass* _tmp166_;
		ValaObjectType* _tmp167_;
		ValaObjectType* _tmp168_;
		gboolean _tmp169_;
		_tmp162_ = vala_foreach_statement_get_collection (stmt);
		_tmp163_ = _tmp162_;
		_tmp164_ = vala_expression_get_value_type (_tmp163_);
		_tmp165_ = _tmp164_;
		_tmp166_ = ((ValaCCodeBaseModule*) self)->glist_type;
		_tmp167_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp166_);
		_tmp168_ = _tmp167_;
		_tmp169_ = vala_data_type_compatible (_tmp165_, (ValaDataType*) _tmp168_);
		_vala_code_node_unref0 (_tmp168_);
		if (_tmp169_) {
			_tmp161_ = TRUE;
		} else {
			ValaExpression* _tmp170_;
			ValaExpression* _tmp171_;
			ValaDataType* _tmp172_;
			ValaDataType* _tmp173_;
			ValaClass* _tmp174_;
			ValaObjectType* _tmp175_;
			ValaObjectType* _tmp176_;
			_tmp170_ = vala_foreach_statement_get_collection (stmt);
			_tmp171_ = _tmp170_;
			_tmp172_ = vala_expression_get_value_type (_tmp171_);
			_tmp173_ = _tmp172_;
			_tmp174_ = ((ValaCCodeBaseModule*) self)->gslist_type;
			_tmp175_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp174_);
			_tmp176_ = _tmp175_;
			_tmp161_ = vala_data_type_compatible (_tmp173_, (ValaDataType*) _tmp176_);
			_vala_code_node_unref0 (_tmp176_);
		}
		if (_tmp161_) {
			ValaLocalVariable* iterator_variable = NULL;
			ValaDataType* _tmp177_;
			ValaDataType* _tmp178_;
			ValaDataType* _tmp179_;
			const gchar* _tmp180_;
			const gchar* _tmp181_;
			gchar* _tmp182_;
			gchar* _tmp183_;
			ValaLocalVariable* _tmp184_;
			ValaLocalVariable* _tmp185_;
			ValaLocalVariable* _tmp186_;
			gchar* it_name = NULL;
			ValaLocalVariable* _tmp187_;
			gchar* _tmp188_;
			ValaCCodeBinaryExpression* ccond = NULL;
			const gchar* _tmp189_;
			ValaCCodeExpression* _tmp190_;
			ValaCCodeExpression* _tmp191_;
			ValaCCodeConstant* _tmp192_;
			ValaCCodeConstant* _tmp193_;
			ValaCCodeBinaryExpression* _tmp194_;
			ValaCCodeBinaryExpression* _tmp195_;
			ValaCCodeFunction* _tmp196_;
			ValaCCodeFunction* _tmp197_;
			const gchar* _tmp198_;
			ValaCCodeExpression* _tmp199_;
			ValaCCodeExpression* _tmp200_;
			ValaLocalVariable* _tmp201_;
			gchar* _tmp202_;
			gchar* _tmp203_;
			ValaCCodeExpression* _tmp204_;
			ValaCCodeExpression* _tmp205_;
			ValaCCodeAssignment* _tmp206_;
			ValaCCodeAssignment* _tmp207_;
			ValaCCodeBinaryExpression* _tmp208_;
			const gchar* _tmp209_;
			ValaCCodeExpression* _tmp210_;
			ValaCCodeExpression* _tmp211_;
			const gchar* _tmp212_;
			ValaCCodeExpression* _tmp213_;
			ValaCCodeExpression* _tmp214_;
			ValaCCodeMemberAccess* _tmp215_;
			ValaCCodeMemberAccess* _tmp216_;
			ValaCCodeAssignment* _tmp217_;
			ValaCCodeAssignment* _tmp218_;
			ValaCCodeExpression* element_expr = NULL;
			const gchar* _tmp219_;
			ValaCCodeExpression* _tmp220_;
			ValaCCodeExpression* _tmp221_;
			ValaCCodeMemberAccess* _tmp222_;
			ValaCCodeExpression* _tmp223_;
			ValaDataType* _tmp224_;
			ValaList* _tmp225_;
			gint _tmp226_;
			gint _tmp227_;
			ValaDataType* element_data_type = NULL;
			ValaDataType* _tmp230_;
			ValaList* _tmp231_;
			gpointer _tmp232_;
			ValaDataType* _tmp233_;
			ValaDataType* _tmp234_;
			ValaDataType* _tmp235_;
			ValaDataType* _tmp236_;
			ValaCCodeExpression* _tmp237_;
			ValaDataType* _tmp238_;
			ValaCCodeExpression* _tmp239_;
			ValaDataType* _tmp240_;
			ValaCCodeExpression* _tmp241_;
			ValaGLibValue* _tmp242_;
			ValaGLibValue* _tmp243_;
			ValaDataType* _tmp244_;
			ValaDataType* _tmp245_;
			ValaTargetValue* _tmp246_;
			ValaTargetValue* _tmp247_;
			ValaCCodeExpression* _tmp248_;
			ValaCCodeExpression* _tmp249_;
			ValaLocalVariable* _tmp250_;
			ValaLocalVariable* _tmp251_;
			ValaCCodeFunction* _tmp252_;
			ValaCCodeFunction* _tmp253_;
			ValaLocalVariable* _tmp254_;
			ValaLocalVariable* _tmp255_;
			gchar* _tmp256_;
			gchar* _tmp257_;
			ValaCCodeExpression* _tmp258_;
			ValaCCodeExpression* _tmp259_;
			ValaCCodeExpression* _tmp260_;
			ValaBlock* _tmp261_;
			ValaBlock* _tmp262_;
			ValaCCodeFunction* _tmp263_;
			ValaCCodeFunction* _tmp264_;
			_tmp177_ = collection_type;
			_tmp178_ = vala_data_type_copy (_tmp177_);
			_tmp179_ = _tmp178_;
			_tmp180_ = vala_foreach_statement_get_variable_name (stmt);
			_tmp181_ = _tmp180_;
			_tmp182_ = g_strconcat (_tmp181_, "_it", NULL);
			_tmp183_ = _tmp182_;
			_tmp184_ = vala_local_variable_new (_tmp179_, _tmp183_, NULL, NULL);
			_tmp185_ = _tmp184_;
			_g_free0 (_tmp183_);
			_vala_code_node_unref0 (_tmp179_);
			iterator_variable = _tmp185_;
			_tmp186_ = iterator_variable;
			vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp186_);
			_tmp187_ = iterator_variable;
			_tmp188_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp187_);
			it_name = _tmp188_;
			_tmp189_ = it_name;
			_tmp190_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp189_);
			_tmp191_ = _tmp190_;
			_tmp192_ = vala_ccode_constant_new ("NULL");
			_tmp193_ = _tmp192_;
			_tmp194_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_INEQUALITY, _tmp191_, (ValaCCodeExpression*) _tmp193_);
			_tmp195_ = _tmp194_;
			_vala_ccode_node_unref0 (_tmp193_);
			_vala_ccode_node_unref0 (_tmp191_);
			ccond = _tmp195_;
			_tmp196_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp197_ = _tmp196_;
			_tmp198_ = it_name;
			_tmp199_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp198_);
			_tmp200_ = _tmp199_;
			_tmp201_ = collection_backup;
			_tmp202_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp201_);
			_tmp203_ = _tmp202_;
			_tmp204_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp203_);
			_tmp205_ = _tmp204_;
			_tmp206_ = vala_ccode_assignment_new (_tmp200_, _tmp205_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp207_ = _tmp206_;
			_tmp208_ = ccond;
			_tmp209_ = it_name;
			_tmp210_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp209_);
			_tmp211_ = _tmp210_;
			_tmp212_ = it_name;
			_tmp213_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp212_);
			_tmp214_ = _tmp213_;
			_tmp215_ = vala_ccode_member_access_new_pointer (_tmp214_, "next");
			_tmp216_ = _tmp215_;
			_tmp217_ = vala_ccode_assignment_new (_tmp211_, (ValaCCodeExpression*) _tmp216_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
			_tmp218_ = _tmp217_;
			vala_ccode_function_open_for (_tmp197_, (ValaCCodeExpression*) _tmp207_, (ValaCCodeExpression*) _tmp208_, (ValaCCodeExpression*) _tmp218_);
			_vala_ccode_node_unref0 (_tmp218_);
			_vala_ccode_node_unref0 (_tmp216_);
			_vala_ccode_node_unref0 (_tmp214_);
			_vala_ccode_node_unref0 (_tmp211_);
			_vala_ccode_node_unref0 (_tmp207_);
			_vala_ccode_node_unref0 (_tmp205_);
			_g_free0 (_tmp203_);
			_vala_ccode_node_unref0 (_tmp200_);
			_tmp219_ = it_name;
			_tmp220_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp219_);
			_tmp221_ = _tmp220_;
			_tmp222_ = vala_ccode_member_access_new_pointer (_tmp221_, "data");
			_tmp223_ = (ValaCCodeExpression*) _tmp222_;
			_vala_ccode_node_unref0 (_tmp221_);
			element_expr = _tmp223_;
			_tmp224_ = collection_type;
			_tmp225_ = vala_data_type_get_type_arguments (_tmp224_);
			_tmp226_ = vala_collection_get_size ((ValaCollection*) _tmp225_);
			_tmp227_ = _tmp226_;
			if (_tmp227_ != 1) {
				ValaSourceReference* _tmp228_;
				ValaSourceReference* _tmp229_;
				_tmp228_ = vala_code_node_get_source_reference ((ValaCodeNode*) stmt);
				_tmp229_ = _tmp228_;
				vala_report_error (_tmp229_, "internal error: missing generic type argument");
				vala_code_node_set_error ((ValaCodeNode*) stmt, TRUE);
				_vala_ccode_node_unref0 (element_expr);
				_vala_ccode_node_unref0 (ccond);
				_g_free0 (it_name);
				_vala_code_node_unref0 (iterator_variable);
				_vala_code_node_unref0 (array_type);
				_vala_code_node_unref0 (collection_type);
				_vala_code_node_unref0 (collection_backup);
				return;
			}
			_tmp230_ = collection_type;
			_tmp231_ = vala_data_type_get_type_arguments (_tmp230_);
			_tmp232_ = vala_list_get (_tmp231_, 0);
			_tmp233_ = (ValaDataType*) _tmp232_;
			_tmp234_ = vala_data_type_copy (_tmp233_);
			_tmp235_ = _tmp234_;
			_vala_code_node_unref0 (_tmp233_);
			element_data_type = _tmp235_;
			_tmp236_ = element_data_type;
			vala_data_type_set_value_owned (_tmp236_, FALSE);
			_tmp237_ = element_expr;
			_tmp238_ = element_data_type;
			_tmp239_ = vala_ccode_base_module_convert_from_generic_pointer ((ValaCCodeBaseModule*) self, _tmp237_, _tmp238_);
			_vala_ccode_node_unref0 (element_expr);
			element_expr = _tmp239_;
			_tmp240_ = element_data_type;
			_tmp241_ = element_expr;
			_tmp242_ = vala_glib_value_new (_tmp240_, _tmp241_, FALSE);
			_tmp243_ = _tmp242_;
			_tmp244_ = vala_foreach_statement_get_type_reference (stmt);
			_tmp245_ = _tmp244_;
			_tmp246_ = vala_ccode_base_module_transform_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp243_, _tmp245_, (ValaCodeNode*) stmt);
			_tmp247_ = _tmp246_;
			_tmp248_ = vala_get_cvalue_ (_tmp247_);
			_tmp249_ = _vala_ccode_node_ref0 (_tmp248_);
			_vala_ccode_node_unref0 (element_expr);
			element_expr = _tmp249_;
			_vala_target_value_unref0 (_tmp247_);
			_vala_target_value_unref0 (_tmp243_);
			_tmp250_ = vala_foreach_statement_get_element_variable (stmt);
			_tmp251_ = _tmp250_;
			vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp251_);
			_tmp252_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp253_ = _tmp252_;
			_tmp254_ = vala_foreach_statement_get_element_variable (stmt);
			_tmp255_ = _tmp254_;
			_tmp256_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp255_);
			_tmp257_ = _tmp256_;
			_tmp258_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp257_);
			_tmp259_ = _tmp258_;
			_tmp260_ = element_expr;
			vala_ccode_function_add_assignment (_tmp253_, _tmp259_, _tmp260_);
			_vala_ccode_node_unref0 (_tmp259_);
			_g_free0 (_tmp257_);
			_tmp261_ = vala_foreach_statement_get_body (stmt);
			_tmp262_ = _tmp261_;
			vala_code_node_emit ((ValaCodeNode*) _tmp262_, (ValaCodeGenerator*) self);
			_tmp263_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
			_tmp264_ = _tmp263_;
			vala_ccode_function_close (_tmp264_);
			_vala_code_node_unref0 (element_data_type);
			_vala_ccode_node_unref0 (element_expr);
			_vala_ccode_node_unref0 (ccond);
			_g_free0 (it_name);
			_vala_code_node_unref0 (iterator_variable);
		} else {
			ValaExpression* _tmp265_;
			ValaExpression* _tmp266_;
			ValaDataType* _tmp267_;
			ValaDataType* _tmp268_;
			ValaClass* _tmp269_;
			ValaObjectType* _tmp270_;
			ValaObjectType* _tmp271_;
			gboolean _tmp272_;
			_tmp265_ = vala_foreach_statement_get_collection (stmt);
			_tmp266_ = _tmp265_;
			_tmp267_ = vala_expression_get_value_type (_tmp266_);
			_tmp268_ = _tmp267_;
			_tmp269_ = ((ValaCCodeBaseModule*) self)->gvaluearray_type;
			_tmp270_ = vala_object_type_new ((ValaObjectTypeSymbol*) _tmp269_);
			_tmp271_ = _tmp270_;
			_tmp272_ = vala_data_type_compatible (_tmp268_, (ValaDataType*) _tmp271_);
			_vala_code_node_unref0 (_tmp271_);
			if (_tmp272_) {
				ValaLocalVariable* iterator_variable = NULL;
				ValaDataType* _tmp273_;
				ValaDataType* _tmp274_;
				ValaDataType* _tmp275_;
				const gchar* _tmp276_;
				const gchar* _tmp277_;
				gchar* _tmp278_;
				gchar* _tmp279_;
				ValaLocalVariable* _tmp280_;
				ValaLocalVariable* _tmp281_;
				ValaLocalVariable* _tmp282_;
				gchar* arr_index = NULL;
				ValaLocalVariable* _tmp283_;
				gchar* _tmp284_;
				gchar* _tmp285_;
				gchar* _tmp286_;
				gchar* _tmp287_;
				ValaCCodeBinaryExpression* ccond = NULL;
				const gchar* _tmp288_;
				ValaCCodeExpression* _tmp289_;
				ValaCCodeExpression* _tmp290_;
				ValaLocalVariable* _tmp291_;
				gchar* _tmp292_;
				gchar* _tmp293_;
				ValaCCodeExpression* _tmp294_;
				ValaCCodeExpression* _tmp295_;
				ValaCCodeMemberAccess* _tmp296_;
				ValaCCodeMemberAccess* _tmp297_;
				ValaCCodeBinaryExpression* _tmp298_;
				ValaCCodeBinaryExpression* _tmp299_;
				ValaCCodeFunction* _tmp300_;
				ValaCCodeFunction* _tmp301_;
				const gchar* _tmp302_;
				ValaCCodeExpression* _tmp303_;
				ValaCCodeExpression* _tmp304_;
				ValaCCodeConstant* _tmp305_;
				ValaCCodeConstant* _tmp306_;
				ValaCCodeAssignment* _tmp307_;
				ValaCCodeAssignment* _tmp308_;
				ValaCCodeBinaryExpression* _tmp309_;
				const gchar* _tmp310_;
				ValaCCodeExpression* _tmp311_;
				ValaCCodeExpression* _tmp312_;
				const gchar* _tmp313_;
				ValaCCodeExpression* _tmp314_;
				ValaCCodeExpression* _tmp315_;
				ValaCCodeConstant* _tmp316_;
				ValaCCodeConstant* _tmp317_;
				ValaCCodeBinaryExpression* _tmp318_;
				ValaCCodeBinaryExpression* _tmp319_;
				ValaCCodeAssignment* _tmp320_;
				ValaCCodeAssignment* _tmp321_;
				ValaCCodeFunctionCall* get_item = NULL;
				ValaCCodeIdentifier* _tmp322_;
				ValaCCodeIdentifier* _tmp323_;
				ValaCCodeFunctionCall* _tmp324_;
				ValaCCodeFunctionCall* _tmp325_;
				ValaCCodeFunctionCall* _tmp326_;
				ValaLocalVariable* _tmp327_;
				gchar* _tmp328_;
				gchar* _tmp329_;
				ValaCCodeExpression* _tmp330_;
				ValaCCodeExpression* _tmp331_;
				ValaCCodeFunctionCall* _tmp332_;
				const gchar* _tmp333_;
				ValaCCodeExpression* _tmp334_;
				ValaCCodeExpression* _tmp335_;
				ValaCCodeExpression* element_expr = NULL;
				ValaCCodeFunctionCall* _tmp336_;
				ValaCCodeUnaryExpression* _tmp337_;
				ValaDataType* _tmp338_;
				ValaDataType* _tmp339_;
				gboolean _tmp340_;
				gboolean _tmp341_;
				ValaLocalVariable* _tmp354_;
				ValaLocalVariable* _tmp355_;
				ValaCCodeFunction* _tmp356_;
				ValaCCodeFunction* _tmp357_;
				ValaLocalVariable* _tmp358_;
				ValaLocalVariable* _tmp359_;
				gchar* _tmp360_;
				gchar* _tmp361_;
				ValaCCodeExpression* _tmp362_;
				ValaCCodeExpression* _tmp363_;
				ValaCCodeExpression* _tmp364_;
				ValaBlock* _tmp365_;
				ValaBlock* _tmp366_;
				ValaCCodeFunction* _tmp367_;
				ValaCCodeFunction* _tmp368_;
				_tmp273_ = ((ValaCCodeBaseModule*) self)->uint_type;
				_tmp274_ = vala_data_type_copy (_tmp273_);
				_tmp275_ = _tmp274_;
				_tmp276_ = vala_foreach_statement_get_variable_name (stmt);
				_tmp277_ = _tmp276_;
				_tmp278_ = g_strdup_printf ("%s_index", _tmp277_);
				_tmp279_ = _tmp278_;
				_tmp280_ = vala_local_variable_new (_tmp275_, _tmp279_, NULL, NULL);
				_tmp281_ = _tmp280_;
				_g_free0 (_tmp279_);
				_vala_code_node_unref0 (_tmp275_);
				iterator_variable = _tmp281_;
				_tmp282_ = iterator_variable;
				vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp282_);
				_tmp283_ = iterator_variable;
				_tmp284_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp283_);
				_tmp285_ = _tmp284_;
				_tmp286_ = vala_ccode_base_module_get_variable_cname ((ValaCCodeBaseModule*) self, _tmp285_);
				_tmp287_ = _tmp286_;
				_g_free0 (_tmp285_);
				arr_index = _tmp287_;
				_tmp288_ = arr_index;
				_tmp289_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp288_);
				_tmp290_ = _tmp289_;
				_tmp291_ = collection_backup;
				_tmp292_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp291_);
				_tmp293_ = _tmp292_;
				_tmp294_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp293_);
				_tmp295_ = _tmp294_;
				_tmp296_ = vala_ccode_member_access_new_pointer (_tmp295_, "n_values");
				_tmp297_ = _tmp296_;
				_tmp298_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_LESS_THAN, _tmp290_, (ValaCCodeExpression*) _tmp297_);
				_tmp299_ = _tmp298_;
				_vala_ccode_node_unref0 (_tmp297_);
				_vala_ccode_node_unref0 (_tmp295_);
				_g_free0 (_tmp293_);
				_vala_ccode_node_unref0 (_tmp290_);
				ccond = _tmp299_;
				_tmp300_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp301_ = _tmp300_;
				_tmp302_ = arr_index;
				_tmp303_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp302_);
				_tmp304_ = _tmp303_;
				_tmp305_ = vala_ccode_constant_new ("0");
				_tmp306_ = _tmp305_;
				_tmp307_ = vala_ccode_assignment_new (_tmp304_, (ValaCCodeExpression*) _tmp306_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
				_tmp308_ = _tmp307_;
				_tmp309_ = ccond;
				_tmp310_ = arr_index;
				_tmp311_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp310_);
				_tmp312_ = _tmp311_;
				_tmp313_ = arr_index;
				_tmp314_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp313_);
				_tmp315_ = _tmp314_;
				_tmp316_ = vala_ccode_constant_new ("1");
				_tmp317_ = _tmp316_;
				_tmp318_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_PLUS, _tmp315_, (ValaCCodeExpression*) _tmp317_);
				_tmp319_ = _tmp318_;
				_tmp320_ = vala_ccode_assignment_new (_tmp312_, (ValaCCodeExpression*) _tmp319_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
				_tmp321_ = _tmp320_;
				vala_ccode_function_open_for (_tmp301_, (ValaCCodeExpression*) _tmp308_, (ValaCCodeExpression*) _tmp309_, (ValaCCodeExpression*) _tmp321_);
				_vala_ccode_node_unref0 (_tmp321_);
				_vala_ccode_node_unref0 (_tmp319_);
				_vala_ccode_node_unref0 (_tmp317_);
				_vala_ccode_node_unref0 (_tmp315_);
				_vala_ccode_node_unref0 (_tmp312_);
				_vala_ccode_node_unref0 (_tmp308_);
				_vala_ccode_node_unref0 (_tmp306_);
				_vala_ccode_node_unref0 (_tmp304_);
				_tmp322_ = vala_ccode_identifier_new ("g_value_array_get_nth");
				_tmp323_ = _tmp322_;
				_tmp324_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp323_);
				_tmp325_ = _tmp324_;
				_vala_ccode_node_unref0 (_tmp323_);
				get_item = _tmp325_;
				_tmp326_ = get_item;
				_tmp327_ = collection_backup;
				_tmp328_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp327_);
				_tmp329_ = _tmp328_;
				_tmp330_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp329_);
				_tmp331_ = _tmp330_;
				vala_ccode_function_call_add_argument (_tmp326_, _tmp331_);
				_vala_ccode_node_unref0 (_tmp331_);
				_g_free0 (_tmp329_);
				_tmp332_ = get_item;
				_tmp333_ = arr_index;
				_tmp334_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp333_);
				_tmp335_ = _tmp334_;
				vala_ccode_function_call_add_argument (_tmp332_, _tmp335_);
				_vala_ccode_node_unref0 (_tmp335_);
				_tmp336_ = get_item;
				_tmp337_ = vala_ccode_unary_expression_new (VALA_CCODE_UNARY_OPERATOR_POINTER_INDIRECTION, (ValaCCodeExpression*) _tmp336_);
				element_expr = (ValaCCodeExpression*) _tmp337_;
				_tmp338_ = vala_foreach_statement_get_type_reference (stmt);
				_tmp339_ = _tmp338_;
				_tmp340_ = vala_data_type_get_value_owned (_tmp339_);
				_tmp341_ = _tmp340_;
				if (_tmp341_) {
					ValaDataType* _tmp342_;
					ValaDataType* _tmp343_;
					ValaCCodeExpression* _tmp344_;
					ValaGLibValue* _tmp345_;
					ValaGLibValue* _tmp346_;
					ValaStruct* _tmp347_;
					ValaStructValueType* _tmp348_;
					ValaStructValueType* _tmp349_;
					ValaTargetValue* _tmp350_;
					ValaTargetValue* _tmp351_;
					ValaCCodeExpression* _tmp352_;
					ValaCCodeExpression* _tmp353_;
					_tmp342_ = vala_foreach_statement_get_type_reference (stmt);
					_tmp343_ = _tmp342_;
					_tmp344_ = element_expr;
					_tmp345_ = vala_glib_value_new (_tmp343_, _tmp344_, FALSE);
					_tmp346_ = _tmp345_;
					_tmp347_ = ((ValaCCodeBaseModule*) self)->gvalue_type;
					_tmp348_ = vala_struct_value_type_new (_tmp347_);
					_tmp349_ = _tmp348_;
					_tmp350_ = vala_ccode_base_module_copy_value ((ValaCCodeBaseModule*) self, (ValaTargetValue*) _tmp346_, (ValaCodeNode*) _tmp349_);
					_tmp351_ = _tmp350_;
					_tmp352_ = vala_get_cvalue_ (_tmp351_);
					_tmp353_ = _vala_ccode_node_ref0 (_tmp352_);
					_vala_ccode_node_unref0 (element_expr);
					element_expr = _tmp353_;
					_vala_target_value_unref0 (_tmp351_);
					_vala_code_node_unref0 (_tmp349_);
					_vala_target_value_unref0 (_tmp346_);
				}
				_tmp354_ = vala_foreach_statement_get_element_variable (stmt);
				_tmp355_ = _tmp354_;
				vala_code_visitor_visit_local_variable ((ValaCodeVisitor*) self, _tmp355_);
				_tmp356_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp357_ = _tmp356_;
				_tmp358_ = vala_foreach_statement_get_element_variable (stmt);
				_tmp359_ = _tmp358_;
				_tmp360_ = vala_ccode_base_module_get_local_cname ((ValaCCodeBaseModule*) self, _tmp359_);
				_tmp361_ = _tmp360_;
				_tmp362_ = vala_ccode_base_module_get_variable_cexpression ((ValaCCodeBaseModule*) self, _tmp361_);
				_tmp363_ = _tmp362_;
				_tmp364_ = element_expr;
				vala_ccode_function_add_assignment (_tmp357_, _tmp363_, _tmp364_);
				_vala_ccode_node_unref0 (_tmp363_);
				_g_free0 (_tmp361_);
				_tmp365_ = vala_foreach_statement_get_body (stmt);
				_tmp366_ = _tmp365_;
				vala_code_node_emit ((ValaCodeNode*) _tmp366_, (ValaCodeGenerator*) self);
				_tmp367_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp368_ = _tmp367_;
				vala_ccode_function_close (_tmp368_);
				_vala_ccode_node_unref0 (element_expr);
				_vala_ccode_node_unref0 (get_item);
				_vala_ccode_node_unref0 (ccond);
				_g_free0 (arr_index);
				_vala_code_node_unref0 (iterator_variable);
			} else {
				ValaSourceReference* _tmp369_;
				ValaSourceReference* _tmp370_;
				_tmp369_ = vala_code_node_get_source_reference ((ValaCodeNode*) stmt);
				_tmp370_ = _tmp369_;
				vala_report_error (_tmp370_, "internal error: unsupported collection type");
				vala_code_node_set_error ((ValaCodeNode*) stmt, TRUE);
				_vala_code_node_unref0 (array_type);
				_vala_code_node_unref0 (collection_type);
				_vala_code_node_unref0 (collection_backup);
				return;
			}
		}
	}
	{
		ValaList* _local_list = NULL;
		ValaList* _tmp371_;
		ValaList* _tmp372_;
		gint _local_size = 0;
		ValaList* _tmp373_;
		gint _tmp374_;
		gint _tmp375_;
		gint _local_index = 0;
		_tmp371_ = vala_block_get_local_variables ((ValaBlock*) stmt);
		_tmp372_ = _vala_iterable_ref0 (_tmp371_);
		_local_list = _tmp372_;
		_tmp373_ = _local_list;
		_tmp374_ = vala_collection_get_size ((ValaCollection*) _tmp373_);
		_tmp375_ = _tmp374_;
		_local_size = _tmp375_;
		_local_index = -1;
		while (TRUE) {
			gint _tmp376_;
			gint _tmp377_;
			ValaLocalVariable* local = NULL;
			ValaList* _tmp378_;
			gpointer _tmp379_;
			ValaLocalVariable* _tmp380_;
			ValaDataType* _tmp381_;
			ValaDataType* _tmp382_;
			_local_index = _local_index + 1;
			_tmp376_ = _local_index;
			_tmp377_ = _local_size;
			if (!(_tmp376_ < _tmp377_)) {
				break;
			}
			_tmp378_ = _local_list;
			_tmp379_ = vala_list_get (_tmp378_, _local_index);
			local = (ValaLocalVariable*) _tmp379_;
			_tmp380_ = local;
			_tmp381_ = vala_variable_get_variable_type ((ValaVariable*) _tmp380_);
			_tmp382_ = _tmp381_;
			if (vala_ccode_base_module_requires_destroy (_tmp382_)) {
				ValaCCodeFunction* _tmp383_;
				ValaCCodeFunction* _tmp384_;
				ValaLocalVariable* _tmp385_;
				ValaCCodeExpression* _tmp386_;
				ValaCCodeExpression* _tmp387_;
				_tmp383_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
				_tmp384_ = _tmp383_;
				_tmp385_ = local;
				_tmp386_ = vala_ccode_base_module_destroy_local ((ValaCCodeBaseModule*) self, _tmp385_);
				_tmp387_ = _tmp386_;
				vala_ccode_function_add_expression (_tmp384_, _tmp387_);
				_vala_ccode_node_unref0 (_tmp387_);
			}
			_vala_code_node_unref0 (local);
		}
		_vala_iterable_unref0 (_local_list);
	}
	_tmp388_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp389_ = _tmp388_;
	vala_ccode_function_close (_tmp389_);
	_vala_code_node_unref0 (array_type);
	_vala_code_node_unref0 (collection_type);
	_vala_code_node_unref0 (collection_backup);
}

static void
vala_ccode_control_flow_module_real_visit_break_statement (ValaCodeVisitor* base,
                                                           ValaBreakStatement* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_current_symbol ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_base_module_append_local_free ((ValaCCodeBaseModule*) self, _tmp1_, (ValaStatement*) stmt, NULL);
	_tmp2_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp3_ = _tmp2_;
	vala_ccode_function_add_break (_tmp3_);
}

static void
vala_ccode_control_flow_module_real_visit_continue_statement (ValaCodeVisitor* base,
                                                              ValaContinueStatement* stmt)
{
	ValaCCodeControlFlowModule * self;
	ValaSymbol* _tmp0_;
	ValaSymbol* _tmp1_;
	ValaCCodeFunction* _tmp2_;
	ValaCCodeFunction* _tmp3_;
	self = (ValaCCodeControlFlowModule*) base;
	g_return_if_fail (stmt != NULL);
	_tmp0_ = vala_ccode_base_module_get_current_symbol ((ValaCCodeBaseModule*) self);
	_tmp1_ = _tmp0_;
	vala_ccode_base_module_append_local_free ((ValaCCodeBaseModule*) self, _tmp1_, (ValaStatement*) stmt, NULL);
	_tmp2_ = vala_ccode_base_module_get_ccode ((ValaCCodeBaseModule*) self);
	_tmp3_ = _tmp2_;
	vala_ccode_function_add_continue (_tmp3_);
}

ValaCCodeControlFlowModule*
vala_ccode_control_flow_module_construct (GType object_type)
{
	ValaCCodeControlFlowModule* self = NULL;
	self = (ValaCCodeControlFlowModule*) vala_ccode_method_module_construct (object_type);
	return self;
}

static void
vala_ccode_control_flow_module_class_init (ValaCCodeControlFlowModuleClass * klass,
                                           gpointer klass_data)
{
	vala_ccode_control_flow_module_parent_class = g_type_class_peek_parent (klass);
	((ValaCodeVisitorClass *) klass)->visit_if_statement = (void (*) (ValaCodeVisitor*, ValaIfStatement*)) vala_ccode_control_flow_module_real_visit_if_statement;
	((ValaCodeVisitorClass *) klass)->visit_switch_statement = (void (*) (ValaCodeVisitor*, ValaSwitchStatement*)) vala_ccode_control_flow_module_real_visit_switch_statement;
	((ValaCodeVisitorClass *) klass)->visit_switch_label = (void (*) (ValaCodeVisitor*, ValaSwitchLabel*)) vala_ccode_control_flow_module_real_visit_switch_label;
	((ValaCodeVisitorClass *) klass)->visit_loop = (void (*) (ValaCodeVisitor*, ValaLoop*)) vala_ccode_control_flow_module_real_visit_loop;
	((ValaCodeVisitorClass *) klass)->visit_foreach_statement = (void (*) (ValaCodeVisitor*, ValaForeachStatement*)) vala_ccode_control_flow_module_real_visit_foreach_statement;
	((ValaCodeVisitorClass *) klass)->visit_break_statement = (void (*) (ValaCodeVisitor*, ValaBreakStatement*)) vala_ccode_control_flow_module_real_visit_break_statement;
	((ValaCodeVisitorClass *) klass)->visit_continue_statement = (void (*) (ValaCodeVisitor*, ValaContinueStatement*)) vala_ccode_control_flow_module_real_visit_continue_statement;
}

static void
vala_ccode_control_flow_module_instance_init (ValaCCodeControlFlowModule * self,
                                              gpointer klass)
{
}

static GType
vala_ccode_control_flow_module_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ValaCCodeControlFlowModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_ccode_control_flow_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaCCodeControlFlowModule), 0, (GInstanceInitFunc) vala_ccode_control_flow_module_instance_init, NULL };
	GType vala_ccode_control_flow_module_type_id;
	vala_ccode_control_flow_module_type_id = g_type_register_static (VALA_TYPE_CCODE_METHOD_MODULE, "ValaCCodeControlFlowModule", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	return vala_ccode_control_flow_module_type_id;
}

GType
vala_ccode_control_flow_module_get_type (void)
{
	static volatile gsize vala_ccode_control_flow_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_ccode_control_flow_module_type_id__volatile)) {
		GType vala_ccode_control_flow_module_type_id;
		vala_ccode_control_flow_module_type_id = vala_ccode_control_flow_module_get_type_once ();
		g_once_init_leave (&vala_ccode_control_flow_module_type_id__volatile, vala_ccode_control_flow_module_type_id);
	}
	return vala_ccode_control_flow_module_type_id__volatile;
}

